name: 'Build Installer'

on:
  repository_dispatch:
    types: [nsis_publish]

env:
  repository: Azbooka/idesk-setup
  studio_name: azbooka_editor.zip
  editor_name: idesk_studio.zip
  version: ${{ github.event.client_payload.ref }}

jobs:
  build-installer:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download release
        shell: bash
        run: |
          echo "${{ secrets.BUILD_TOKEN }}" | gh auth login --with-token
          gh release download --repo ${{ env.repository }} --pattern '*.exe'

      - name: Upload release ${{ env.version }}
        if: ${{ success() }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.BUILD_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: false
          title: 'latest build'
          files: |
            *.exe
